=== vries/gdb/gdb/features/gdb-target.dtd
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- The root element of a GDB target description is <target>.  -->

<!-- The osabi and compatible elements were added post GDB 6.8.  The version
     wasn't bumped, since older GDBs silently ignore unknown elements.  -->

<!ELEMENT target	(architecture?, osabi?, compatible*, xi:include*, feature*)>
<!ATTLIST target
	version		CDATA	#FIXED "1.0"
	xmlns:xi	CDATA   #FIXED "http://www.w3.org/2001/XInclude">
<!ELEMENT architecture	(#PCDATA)>

<!ELEMENT osabi	(#PCDATA)>

<!ELEMENT compatible	(#PCDATA)>

<!ELEMENT feature
	((vector | flags | struct | union )*, reg*)>
<!ATTLIST feature
	name		ID	#REQUIRED>

<!ELEMENT reg		(description*)>
<!ATTLIST reg
	name		CDATA	#REQUIRED
	bitsize		CDATA	#REQUIRED
	regnum		CDATA	#IMPLIED
	save-restore	(yes | no) 'yes'
	type		CDATA	'int'
	group		CDATA	#IMPLIED
	>

<!ELEMENT vector	EMPTY>
<!ATTLIST vector
	id		CDATA	#REQUIRED
	type		CDATA	#REQUIRED
	count		CDATA	#REQUIRED>

<!ELEMENT flags		(field+)>
<!ATTLIST flags
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT enum		(evalue+)>
<!ATTLIST enum
	id		CDATA	#REQUIRED
	size		CDATA	#REQUIRED>

<!ELEMENT struct	(field+)>
<!ATTLIST struct
	id		CDATA	#REQUIRED
	size		CDATA	#IMPLIED>

<!ELEMENT union		(field+)>
<!ATTLIST union
	id		CDATA	#REQUIRED>

<!ELEMENT field		EMPTY>
<!ATTLIST field
	name		CDATA	#REQUIRED
	type		CDATA	#IMPLIED
	start		CDATA	#IMPLIED
	end		CDATA	#IMPLIED>

<!ELEMENT evalue	EMPTY>
<!ATTLIST evalue
	name		CDATA	#REQUIRED
	value		CDATA	#REQUIRED>

<!ENTITY % xinclude SYSTEM "xinclude.dtd">
%xinclude;

=== vries/gdb/gdb/features/rs6000/powerpc-602.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="602">
    <!-- codespell:ignore-begin -->
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="tcr" bitsize="32" regnum="124"/>
    <reg name="ibr" bitsize="32"/>
    <reg name="esasrr" bitsize="32"/>
    <reg name="sebr" bitsize="32"/>
    <reg name="ser" bitsize="32"/>
    <reg name="sp" bitsize="32"/>
    <reg name="lt" bitsize="32"/>
    <!-- codespell:ignore-end -->
  </feature>
</target>

=== vries/gdb/gdb/features/rs6000/powerpc-403.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="403">
    <reg name="icdbdr" bitsize="32"/>
    <reg name="esr" bitsize="32"/>
    <reg name="dear" bitsize="32"/>
    <reg name="evpr" bitsize="32"/>
    <reg name="cdbcr" bitsize="32"/>
    <reg name="tsr" bitsize="32"/>
    <reg name="tcr" bitsize="32"/>
    <reg name="pit" bitsize="32"/>
    <reg name="tbhi" bitsize="32"/>
    <reg name="tblo" bitsize="32"/>
    <reg name="srr2" bitsize="32"/>
    <reg name="srr3" bitsize="32"/>
    <reg name="dbsr" bitsize="32"/>
    <reg name="dbcr" bitsize="32"/>
    <reg name="iac1" bitsize="32"/>
    <reg name="iac2" bitsize="32"/>
    <reg name="dac1" bitsize="32"/>
    <reg name="dac2" bitsize="32"/>
    <reg name="dccr" bitsize="32"/>
    <reg name="iccr" bitsize="32"/>
    <reg name="pbl1" bitsize="32"/>
    <reg name="pbu1" bitsize="32"/>
    <reg name="pbl2" bitsize="32"/>
    <reg name="pbu2" bitsize="32"/>
  </feature>
</target>

=== vries/gdb/gdb/features/rs6000/powerpc-601.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- IBM POWER (pre-PowerPC) architecture, user-level view.  We only cover
     user-level SPR's.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate mq.  -->
  <feature name="org.gnu.gdb.power.core">
    <reg name="r0" bitsize="32"/>
    <reg name="r1" bitsize="32"/>
    <reg name="r2" bitsize="32"/>
    <reg name="r3" bitsize="32"/>
    <reg name="r4" bitsize="32"/>
    <reg name="r5" bitsize="32"/>
    <reg name="r6" bitsize="32"/>
    <reg name="r7" bitsize="32"/>
    <reg name="r8" bitsize="32"/>
    <reg name="r9" bitsize="32"/>
    <reg name="r10" bitsize="32"/>
    <reg name="r11" bitsize="32"/>
    <reg name="r12" bitsize="32"/>
    <reg name="r13" bitsize="32"/>
    <reg name="r14" bitsize="32"/>
    <reg name="r15" bitsize="32"/>
    <reg name="r16" bitsize="32"/>
    <reg name="r17" bitsize="32"/>
    <reg name="r18" bitsize="32"/>
    <reg name="r19" bitsize="32"/>
    <reg name="r20" bitsize="32"/>
    <reg name="r21" bitsize="32"/>
    <reg name="r22" bitsize="32"/>
    <reg name="r23" bitsize="32"/>
    <reg name="r24" bitsize="32"/>
    <reg name="r25" bitsize="32"/>
    <reg name="r26" bitsize="32"/>
    <reg name="r27" bitsize="32"/>
    <reg name="r28" bitsize="32"/>
    <reg name="r29" bitsize="32"/>
    <reg name="r30" bitsize="32"/>
    <reg name="r31" bitsize="32"/>

    <reg name="pc" bitsize="32" type="code_ptr" regnum="64"/>
    <reg name="msr" bitsize="32"/>
    <reg name="cr" bitsize="32"/>
    <reg name="lr" bitsize="32" type="code_ptr"/>
    <reg name="ctr" bitsize="32"/>
    <reg name="xer" bitsize="32"/>
    <reg name="mq" bitsize="32" regnum="124"/>
  </feature>

  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="601">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="pir" bitsize="32" regnum="123"/>
    <reg name="rtcu" bitsize="32" regnum="125"/>
    <reg name="rtcl" bitsize="32"/>
  </feature>
</target>

=== vries/gdb/gdb/features/rx.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2019-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <feature name="org.gnu.gdb.rx.core">
    <reg name="r0" bitsize="32" type="data_ptr"/>
    <reg name="r1" bitsize="32" type="uint32"/>
    <reg name="r2" bitsize="32" type="uint32"/>
    <reg name="r3" bitsize="32" type="uint32"/>
    <reg name="r4" bitsize="32" type="uint32"/>
    <reg name="r5" bitsize="32" type="uint32"/>
    <reg name="r6" bitsize="32" type="uint32"/>
    <reg name="r7" bitsize="32" type="uint32"/>
    <reg name="r8" bitsize="32" type="uint32"/>
    <reg name="r9" bitsize="32" type="uint32"/>
    <reg name="r10" bitsize="32" type="uint32"/>
    <reg name="r11" bitsize="32" type="uint32"/>
    <reg name="r12" bitsize="32" type="uint32"/>
    <reg name="r13" bitsize="32" type="uint32"/>
    <reg name="r14" bitsize="32" type="uint32"/>
    <reg name="r15" bitsize="32" type="uint32"/>

    <flags id="psw_flags" size="4">
      <field name="C" start="0" end="0"/>
      <field name="Z" start="1" end="1"/>
      <field name="S" start="2" end="2"/>
      <field name="O" start="3" end="3"/>
      <field name="I" start="16" end="16"/>
      <field name="U" start="17" end="17"/>
      <field name="PM" start="20" end="20"/>
      <field name="IPL0" start="24" end="24"/>
      <field name="IPL1" start="25" end="25"/>
      <field name="IPL2" start="26" end="26"/>
      <field name="IPL3" start="27" end="27"/>
    </flags>

    <flags id="fpsw_flags" size="4">
      <!-- codespell:ignore-begin -->
      <field name="RM0" start="0" end="0"/>
      <field name="RM1" start="1" end="1"/>
      <field name="CV" start="2" end="2"/>
      <field name="CO" start="3" end="3"/>
      <field name="CZ" start="4" end="4"/>
      <field name="CU" start="5" end="5"/>
      <field name="CX" start="6" end="6"/>
      <field name="CE" start="7" end="7"/>
      <field name="DN" start="8" end="8"/>
      <field name="EV" start="10" end="10"/>
      <field name="EO" start="11" end="11"/>
      <field name="EZ" start="12" end="12"/>
      <field name="EU" start="13" end="13"/>
      <field name="EX" start="14" end="14"/>
      <field name="FV" start="26" end="26"/>
      <field name="FO" start="27" end="27"/>
      <field name="FZ" start="28" end="28"/>
      <field name="FU" start="29" end="29"/>
      <field name="FX" start="30" end="30"/>
      <field name="FS" start="31" end="31"/>
      <!-- codespell:ignore-end -->
    </flags>

    <reg name="usp" bitsize="32" type="data_ptr"/>
    <reg name="isp" bitsize="32" type="data_ptr"/>
    <reg name="psw" bitsize="32" type="psw_flags"/>
    <reg name="pc" bitsize="32" type="code_ptr"/>
    <reg name="intb" bitsize="32" type="data_ptr"/>
    <reg name="bpsw" bitsize="32" type="psw_flags"/>
    <reg name="bpc" bitsize="32" type="code_ptr"/>
    <reg name="fintv" bitsize="32" type="code_ptr"/>
    <reg name="fpsw" bitsize="32" type="fpsw_flags"/>
    <reg name="acc" bitsize="64" type="uint64"/>
  </feature>
</target>

=== vries/gdb/gdb/features/arm/arm-core.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2024 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE feature SYSTEM "gdb-target.dtd">
<feature name="org.gnu.gdb.arm.core">
  <flags id="arm_cpsr" size="4">
    <field name="M" start="0" end="4"/>
    <field name="T" start="5" end="5"/>
    <field name="F" start="6" end="6"/>
    <field name="I" start="7" end="7"/>
    <field name="A" start="8" end="8"/>
    <field name="E" start="9" end="9"/>
    <field name="IT72" start="10" end="15"/>
    <field name="GE" start="16" end="19"/>
    <field name="J" start="24" end="24"/>
    <field name="IT10" start="25" end="26"/>
    <field name="Q" start="27" end="27"/>
    <field name="V" start="28" end="28"/>
    <field name="C" start="29" end="29"/>
    <field name="Z" start="30" end="30"/>
    <field name="N" start="31" end="31"/>
  </flags>
  <reg name="r0" bitsize="32" type="uint32"/>
  <reg name="r1" bitsize="32" type="uint32"/>
  <reg name="r2" bitsize="32" type="uint32"/>
  <reg name="r3" bitsize="32" type="uint32"/>
  <reg name="r4" bitsize="32" type="uint32"/>
  <reg name="r5" bitsize="32" type="uint32"/>
  <reg name="r6" bitsize="32" type="uint32"/>
  <reg name="r7" bitsize="32" type="uint32"/>
  <reg name="r8" bitsize="32" type="uint32"/>
  <reg name="r9" bitsize="32" type="uint32"/>
  <reg name="r10" bitsize="32" type="uint32"/>
  <reg name="r11" bitsize="32" type="uint32"/>
  <reg name="r12" bitsize="32" type="uint32"/>
  <reg name="sp" bitsize="32" type="data_ptr"/>
  <reg name="lr" bitsize="32"/>
  <reg name="pc" bitsize="32" type="code_ptr"/>

  <!-- The CPSR is register 25, rather than register 16, because
       the FPA registers historically were placed between the PC
       and the CPSR in the "g" packet.  -->
  <reg name="cpsr" bitsize="32" regnum="25" type="arm_cpsr"/>
</feature>

=== vries/gdb/gdb/features/rs6000/powerpc-603.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- PowerPC 603 or 603e.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>
  <xi:include href="power-oea.xml"/>

  <feature name="603">
    <reg name="hid0" bitsize="32"/>
    <reg name="hid1" bitsize="32"/>
    <reg name="iabr" bitsize="32"/>
    <reg name="dmiss" bitsize="32" regnum="124"/>
    <reg name="dcmp" bitsize="32"/>
    <reg name="hash1" bitsize="32"/>
    <reg name="hash2" bitsize="32"/>
    <reg name="imiss" bitsize="32"/>
    <reg name="icmp" bitsize="32"/>
    <reg name="rpa" bitsize="32"/>
  </feature>
</target>

=== vries/gdb/gdb/features/rs6000/powerpc-405.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2009-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <xi:include href="power-core.xml"/>
  <xi:include href="power-fpu.xml"/>

  <feature name="405">
    <reg name="pvr" bitsize="32" regnum="87"/>
    <reg name="sprg0" bitsize="32" regnum="108"/>
    <reg name="sprg1" bitsize="32"/>
    <reg name="sprg2" bitsize="32"/>
    <reg name="sprg3" bitsize="32"/>
    <reg name="srr0" bitsize="32"/>
    <reg name="srr1" bitsize="32"/>
    <reg name="tbl" bitsize="32"/>
    <reg name="tbu" bitsize="32"/>
    <reg name="icdbdr" bitsize="32" regnum="119"/>
    <reg name="esr" bitsize="32"/>
    <reg name="dear" bitsize="32"/>
    <reg name="evpr" bitsize="32"/>
    <reg name="tsr" bitsize="32" regnum="124"/>
    <reg name="tcr" bitsize="32"/>
    <reg name="pit" bitsize="32"/>
    <reg name="srr2" bitsize="32" regnum="129"/>
    <reg name="srr3" bitsize="32"/>
    <reg name="dbsr" bitsize="32"/>
    <reg name="dbcr" bitsize="32"/>
    <reg name="iac1" bitsize="32"/>
    <reg name="iac2" bitsize="32"/>
    <reg name="dac1" bitsize="32"/>
    <reg name="dac2" bitsize="32"/>
    <reg name="dccr" bitsize="32"/>
    <reg name="iccr" bitsize="32"/>
    <reg name="zpr" bitsize="32" regnum="143"/>
    <reg name="pid" bitsize="32"/>
    <reg name="sgr" bitsize="32"/>
    <reg name="dcwr" bitsize="32"/>
    <reg name="ccr0" bitsize="32" regnum="149"/>
    <reg name="dbcr1" bitsize="32"/>
    <reg name="dvc1" bitsize="32"/>
    <reg name="dvc2" bitsize="32"/>
    <reg name="iac3" bitsize="32"/>
    <reg name="iac4" bitsize="32"/>
    <reg name="sler" bitsize="32"/>
    <reg name="sprg4" bitsize="32"/>
    <reg name="sprg5" bitsize="32"/>
    <reg name="sprg6" bitsize="32"/>
    <reg name="sprg7" bitsize="32"/>
    <reg name="su0r" bitsize="32"/>
    <reg name="usprg0" bitsize="32"/>
  </feature>
</target>

=== vries/gdb/gdb/features/rs6000/rs6000.xml
<?xml version="1.0"?>
<!-- Copyright (C) 2007-2026 Free Software Foundation, Inc.

     Copying and distribution of this file, with or without modification,
     are permitted in any medium without royalty provided the copyright
     notice and this notice are preserved.  -->

<!-- IBM POWER (pre-PowerPC) architecture, user-level view.  We only cover
     user-level SPR's.  -->

<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target xmlns:xi="http://www.w3.org/2001/XInclude">
  <architecture>rs6000:6000</architecture>

  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate mq, cnd, and cnt.  -->
  <feature name="org.gnu.gdb.power.core">
    <reg name="r0" bitsize="32"/>
    <reg name="r1" bitsize="32"/>
    <reg name="r2" bitsize="32"/>
    <reg name="r3" bitsize="32"/>
    <reg name="r4" bitsize="32"/>
    <reg name="r5" bitsize="32"/>
    <reg name="r6" bitsize="32"/>
    <reg name="r7" bitsize="32"/>
    <reg name="r8" bitsize="32"/>
    <reg name="r9" bitsize="32"/>
    <reg name="r10" bitsize="32"/>
    <reg name="r11" bitsize="32"/>
    <reg name="r12" bitsize="32"/>
    <reg name="r13" bitsize="32"/>
    <reg name="r14" bitsize="32"/>
    <reg name="r15" bitsize="32"/>
    <reg name="r16" bitsize="32"/>
    <reg name="r17" bitsize="32"/>
    <reg name="r18" bitsize="32"/>
    <reg name="r19" bitsize="32"/>
    <reg name="r20" bitsize="32"/>
    <reg name="r21" bitsize="32"/>
    <reg name="r22" bitsize="32"/>
    <reg name="r23" bitsize="32"/>
    <reg name="r24" bitsize="32"/>
    <reg name="r25" bitsize="32"/>
    <reg name="r26" bitsize="32"/>
    <reg name="r27" bitsize="32"/>
    <reg name="r28" bitsize="32"/>
    <reg name="r29" bitsize="32"/>
    <reg name="r30" bitsize="32"/>
    <reg name="r31" bitsize="32"/>

    <reg name="pc" bitsize="32" type="code_ptr" regnum="64"/>
    <reg name="msr" bitsize="32"/>
    <reg name="cnd" bitsize="32"/>
    <reg name="lr" bitsize="32" type="code_ptr"/>
    <reg name="cnt" bitsize="32"/>
    <reg name="xer" bitsize="32"/>
    <reg name="mq" bitsize="32"/>
  </feature>

  <!-- This description is slightly different from the standard
       org.gnu.gdb.power.core, to accommodate historical numbering
       for fpscr.  -->
  <feature name="org.gnu.gdb.power.fpu">
    <reg name="f0" bitsize="64" type="ieee_double" regnum="32"/>
    <reg name="f1" bitsize="64" type="ieee_double"/>
    <reg name="f2" bitsize="64" type="ieee_double"/>
    <reg name="f3" bitsize="64" type="ieee_double"/>
    <reg name="f4" bitsize="64" type="ieee_double"/>
    <reg name="f5" bitsize="64" type="ieee_double"/>
    <reg name="f6" bitsize="64" type="ieee_double"/>
    <reg name="f7" bitsize="64" type="ieee_double"/>
    <reg name="f8" bitsize="64" type="ieee_double"/>
    <reg name="f9" bitsize="64" type="ieee_double"/>
    <reg name="f10" bitsize="64" type="ieee_double"/>
    <reg name="f11" bitsize="64" type="ieee_double"/>
    <reg name="f12" bitsize="64" type="ieee_double"/>
    <reg name="f13" bitsize="64" type="ieee_double"/>
    <reg name="f14" bitsize="64" type="ieee_double"/>
    <reg name="f15" bitsize="64" type="ieee_double"/>
    <reg name="f16" bitsize="64" type="ieee_double"/>
    <reg name="f17" bitsize="64" type="ieee_double"/>
    <reg name="f18" bitsize="64" type="ieee_double"/>
    <reg name="f19" bitsize="64" type="ieee_double"/>
    <reg name="f20" bitsize="64" type="ieee_double"/>
    <reg name="f21" bitsize="64" type="ieee_double"/>
    <reg name="f22" bitsize="64" type="ieee_double"/>
    <reg name="f23" bitsize="64" type="ieee_double"/>
    <reg name="f24" bitsize="64" type="ieee_double"/>
    <reg name="f25" bitsize="64" type="ieee_double"/>
    <reg name="f26" bitsize="64" type="ieee_double"/>
    <reg name="f27" bitsize="64" type="ieee_double"/>
    <reg name="f28" bitsize="64" type="ieee_double"/>
    <reg name="f29" bitsize="64" type="ieee_double"/>
    <reg name="f30" bitsize="64" type="ieee_double"/>
    <reg name="f31" bitsize="64" type="ieee_double"/>

    <reg name="fpscr" bitsize="32" group="float" regnum="71"/>
  </feature>
</target>
